#!/bin/sh

# KUNGFU_HOME_DIR=/opt/kungfu

KUNGFU_DATA_DIR=/shared/kungfu
KUNGFU_SOCKETS_DIR=$KUNGFU_DATA_DIR/socket
KUNGFU_LOGGING_DIR=$KUNGFU_DATA_DIR/log
KUNGFU_PID_DIR=$KUNGFU_DATA_DIR/pid
KUNGFU_RUNTIME_DIR=$KUNGFU_DATA_DIR/runtime
KUNGFU_JOURNAL_DIR=$KUNGFU_DATA_DIR/journal


# chown -R bruce:bruce $KUNGFU_HOME_DIR

mkdir -p $KUNGFU_SOCKETS_DIR

mkdir -p $KUNGFU_LOGGING_DIR
mkdir -p $KUNGFU_LOGGING_DIR/supervisor
mkdir -p $KUNGFU_LOGGING_DIR/wingchun
mkdir -p $KUNGFU_LOGGING_DIR/strategy

mkdir -p $KUNGFU_PID_DIR

mkdir -p $KUNGFU_RUNTIME_DIR

mkdir -p $KUNGFU_JOURNAL_DIR
mkdir -p $KUNGFU_JOURNAL_DIR/system
mkdir -p $KUNGFU_JOURNAL_DIR/strategy
mkdir -p $KUNGFU_JOURNAL_DIR/user
mkdir -p $KUNGFU_JOURNAL_DIR/MD/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/OKEX
mkdir -p $KUNGFU_JOURNAL_DIR/MD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/MD_RAW/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_RAW/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_SEND/BINANCE
mkdir -p $KUNGFU_JOURNAL_DIR/TD_Q/BINANCE

chown -R root:root $KUNGFU_DATA_DIR
